name: flutter_ai_toolkit
description: "A set of AI chat-related widgets for your Flutter app targeting mobile, desktop and web."
version: 0.2.0
homepage: https://github.com/csells/flutter_ai_toolkit

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.4
  image_picker: ^1.1.2
  mime: ^2.0.0
  google_fonts: ^6.2.1
  file_selector: ^1.0.3
  cross_file: ^0.3.4+2
  firebase_vertexai: ^0.2.3
  gap: ^3.0.1
  universal_platform: ^1.1.0
  ollama_dart: ^0.2.1
  waveform_recorder: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
   - family: FatIcons
     fonts:
      - asset: lib/fonts/FatIcons.ttf
