name: flutter_ai_toolkit
description: "A set of AI chat-related widgets for your Flutter app targeting mobile, desktop and web."
version: 0.6.3
homepage: https://github.com/csells/flutter_ai_toolkit

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.4+2
  file_selector: ^1.0.3
  firebase_vertexai: ^1.0.1
  flutter:
    sdk: flutter
  flutter_context_menu: ^0.2.0
  flutter_markdown: ^0.7.4
  flutter_picture_taker: ^0.2.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  mime: ^2.0.0
  universal_platform: ^1.1.0
  uuid: ^4.4.2
  waveform_recorder: ^1.3.0
  
dev_dependencies:
  all_lint_rules_community: ^0.0.42
  flutter_test:
    sdk: flutter

flutter:
  fonts:
   - family: FatIcons
     fonts:
      - asset: lib/fonts/FatIcons.ttf
