/// Flutter icons FatIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FatIcons
///      fonts:
///       - asset: fonts/FatIcons.ttf
///
///
///

// ignore_for_file: dangling_library_doc_comments, public_member_api_docs

import 'package:flutter/widgets.dart';

class FatIcons {
  FatIcons._();

  static const _fontFam = 'FatIcons';
  static const String _fontPkg = 'flutter_ai_toolkit';

  static const IconData submitIcon =
      IconData(0xe800, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData sparkIcon =
      IconData(0xe801, fontFamily: _fontFam, fontPackage: _fontPkg);
}
